name: CI Workflow

on: [push, pull_request]

env:
  MONITORING_TOOL_API_ENDPOINT: ${{ env.MONITORING_TOOL_API_ENDPOINT }}

jobs:
  install_typo3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up database
        run: echo "Setting up database..."
      - name: Download and extract TYPO3
        run: |
          curl -L -o typo3.zip https://get.typo3.org/download
          unzip typo3.zip
      - name: Install TYPO3
        run: echo "Running TYPO3 installation..."

  scan_project:
    needs: install_typo3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Scan PHP libraries from composer.lock
        run: echo "Scanning PHP libraries..."
      - name: Scan JS libraries from package-lock.json
        run: echo "Scanning JS libraries..."
      - name: Create SBOM
        run: echo "Creating Software Bill of Materials (SBOM)..."
      - name: Send SBOM to monitoring tool
        run: |
          curl -X POST -H "Content-Type: application/json" -d @path-to-sbom-file.json $MONITORING_TOOL_API_ENDPOINT

  check_updates:
    needs: scan_project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check PHP vulnerabilities using CodeQL
        uses: github/codeql-action/analyze@v1
        with:
          language: 'php'
      - name: Check JS libraries for vulnerabilities
        run: npm audit --json > audit-result.json

  notify:
    needs: check_updates
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Slack (optional)
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Job ${{ github.job }} of ${{ github.workflow }} by ${{ github.actor }} has encountered an error.'
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
